# Generated by Django 6.0.4 on 2026-04-13 13:08

import django.db.models.deletion
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=7)),
                ('logo_path', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_connected', models.BooleanField(default=False)),
                ('webhook_secret', models.CharField(default=secrets.token_hex, max_length=64)),
                ('auto_accept', models.BooleanField(default=False)),
                ('menu_sync', models.BooleanField(default=True)),
                ('config', models.JSONField(default=dict)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurant_connections', to='integrations.platform')),
            ],
        ),
    ]
